# FORMAT: 
# rule: file(s)
# command underneath it, <TAB>bed once.

# Exercise 1: Make file 1


# Exercise 2: Make file 2 

# Exercise 3: Edit file 2 so it calls file1's foo(), and then compile both. 
# Hmmm...

clean:
	rm -rf *.out *.dSYM